### ISSUE TITLE
[Bug] Failed to decode compiler output with encoding cp1252 with external compilation

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#188]
I'm unsure where this problem comes from:

Given the standard installation and a batch file cobc.bat with the following content:

```cmd
cobc %*
```

I see the background task working fine (errors like "No such file or directory" for copy books). But on using "Compile" I see the error message "Failed to decode compiler output with encoding cp1252" instead of the error message the background task shows.

Why does the background task work but the compile doesn't?

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.5
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
This error comes if the parser cannot convert a sequence bytes to a string using the cp1252 encoding. cobc (or ld.exe) seems to output something that is not decodable using the locale encoding. The differences between the compiler and the linter commands is that the linter command use ``-fsyntax-only``. So both commands are not invoking the exact same program and it is possible that e.g. the linker output some un-decodable character.

Closing because this is a problem on your side and I cannot reproduce.

**Comment by GitMensch** [comment]
> Closing because this is a problem on your side and I cannot reproduce.

Did you tried this on your windows machine with a cobc.bat as described?
As the tested file cannot be compiled (because of the -I../cpy issue) the commands invoked are 100% identical.

**Comment by ColinDuquesnoy** [comment]
> Did you tried this on your windows machine with a cobc.bat as described?

No, not yet... but I never managed to reproduce issue #163 and #165 (those are the same issues, UnicodeDecodeError).

> As the tested file cannot be compiled (because of the -I../cpy issue) the commands invoked are 100% identical.

mmh yes probably, will check that again ;)

**Comment by ColinDuquesnoy** [comment]
I cannot reproduce this bug on my system. The file compile fine using a cobc.bat:

```
C:\Dev\OpenCobolIDE\GnuCOBOL-Win32-MinGW\bin\cobc.bat -x -o C:\Dev\OpenCobolIDE\test\testfiles\bin\TEST-PRINTER.exe -std=default -debug TEST-PRINTER.cbl

C:\Dev\OpenCobolIDE\test\testfiles>cobc -x -o C:\Dev\OpenCobolIDE\test\testfiles\bin\TEST-PRINTER.exe -std=default -debug TEST-PRINTER.cbl 

C:\Dev\OpenCobolIDE\GnuCOBOL-Win32-MinGW\bin\cobc.bat -o C:\Dev\OpenCobolIDE\test\testfiles\bin\VIRTUAL-PRINTER.dll -std=default -debug VIRTUAL-PRINTER.cbl

C:\Dev\OpenCobolIDE\test\testfiles>cobc -o C:\Dev\OpenCobolIDE\test\testfiles\bin\VIRTUAL-PRINTER.dll -std=default -debug VIRTUAL-PRINTER.cbl 
```

I will close this issue as not reproductible.

**Comment by GitMensch** [comment]
Please recheck with the following batch

~~~~~
@echo off
setlocal

:: check of compiler version
if [%1]==[--version] (
   cobc.exe %*
   set rc=%errorlevel%
   goto ende
)

FOR %%O IN (%*) DO CALL :storeopt %%O


:: check working compiler
if [%option%]==[%TEMP%\test.cbl] (
   call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\VCVARS32.bat"
   cobc.exe %*
   set rc=%errorlevel%
   goto ende
)


rem cobc.exe %*
set rc=%errorlevel%
goto end


:storeopt
set option=%1
set optionpath=%~dp1
set optionfile=%~nx1
goto :eof

:end
echo exit with %rc%
endlocal
~~~~~

For testing purposes I've removed the actual cobc call and added a simple output.

**Comment by ColinDuquesnoy** [comment]
I'll check that. Thanks ;)

**Comment by ColinDuquesnoy** [comment]
I still cannot reproduce that bug using your batch :( Here is the output I get:

![capture](https://cloud.githubusercontent.com/assets/1681217/9883706/f91905ce-5bdb-11e5-9424-de0003c3d500.PNG)

I've tried this with both a french and an english system (windows 10).

**Comment by GitMensch** [comment]
Likely has something to do with #204

**Comment by ColinDuquesnoy** [comment]
Does that still happen?

**Comment by GitMensch** [comment]
I've just found out that a file C:\TEMP\TEST.COB that gets compiled with errors (all errors shown perfectly) does result in "Failed to decode compiler output with encoding cp1252" when copied to and opened from a network share with UNC-path \\SERVER\share\TEST.COB. Please recheck this (likely is the main reason for most occurrences of this message in my bug tickets as I open most files via UNC-paths on the machine where I see this error often).

**Comment by ColinDuquesnoy** [comment]
Interesting, I'll recheck that.

**Comment by GitMensch** [comment]
Hi @ColinDuquesnoy,
did you found the time to reproduce it?

**Comment by ColinDuquesnoy** [comment]
Nope, not yet. But I now have esqlOC running in HackEdit ;)
I've (re)assigned this issue to milestone 4.7 so that I don't forget.

**Comment by ColinDuquesnoy** [comment]
So here is the output I get when using and UNC-path:

```
C:\Users\reneg\AppData\Local\Temp\cobc_wrapper.bat -x -o \\diskstation\home\bin\HelloWorld.exe -std=default -debug -v HelloWorld.cbl
'\\diskstation\home'
CMD.EXE a ‚t‚ d‚marr‚ avec le chemin d'accŠs comme r‚pertoire en
cours. Les chemins d'accŠs UNC ne sont pas prise en charge. Utilisation
du r‚pertoire Windows par d‚faut.

C:\Windows>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"  1>NUL 

C:\Windows>call "C:/OpenCobol/cobc.exe" -x -o \\diskstation\home\bin\HelloWorld.exe -std=default -debug -v HelloWorld.cbl 
Command line:	C:/OpenCobol/cobc.exe -x -o \\diskstation\home\bin\HelloWorld.exe -std=default -debug -v HelloWorld.cbl 
cobc: HelloWorld.cbl: No such file or directory

```

**Comment by ColinDuquesnoy** [comment]
So the error is triggered by the cd command in the wrapper batch. If I use a MinGW based compiler then there is no problem.

```
D:\Documents\OpenCobolIDE\GnuCOBOL-Win32-MinGW\bin\cobc.exe -x -o \\diskstation\home\bin\HelloWorld.exe -std=default -debug HelloWorld.cbl
HelloWorld.cbl:8: Error: syntax error, unexpected IDENTIFICATION, expecting FUNCTION-ID or PROGRAM-ID
```

**Comment by ColinDuquesnoy** [comment]
thoughts?

**Comment by GitMensch** [comment]
This error comes from using a batch file for the wrapper (it doesn't support UNC).
For solving this part-issue (only MSC specific, if I see this correct) you would need to find another way for setting the VC vars (I *guess* that you could call it directly and it sets the environment for the whole process [as it's on Windows]).

**Comment by ColinDuquesnoy** [comment]
I found a solution by running vcvarsall.bat and by inspecting it's output for setting up environment variables ("include", "lib", "libpath", "path"). 

I will change the compiler preferences accordingly. 

When using vcvarsall, I need to specify the architecture (currently hardcoded to x86). I plan to add a combo box for the architecture next to the vcvarsall edit box but does it make sense to add it? Do you plan to release 64bit version of GnuCOBOL? Is that supported?

**Comment by ColinDuquesnoy** [comment]
Note for myself: I will also need to update the documentation and the screenshots.

**Comment by GitMensch** [comment]
Nice solution of simply copying the output of vcvarsall (keep in mind to set all this stuff only before compiling [as you are doing for COB_... already] as one may want to change).
And yes, 64bit-versions are used since years (kiska has one, too). At least for Hackedit it would be better to be able to have separate GC-configurations (may sound too big, but I get the clue: I'd configure multiple versions (the version I currently release, the version I currently test, maybe with both x86 and x64, maybe write another which calls a batch which itself opens a ssh connection for compiling on other machines, too,...) - for the linter progress one of these should be markable as "main compiler".

BTW: we would actually use this configuration @work, if it exists already as it's necessary to build for multiple architectures...

**Comment by ColinDuquesnoy** [comment]
In HackEdit you can setup multiple compiler configuration in the preferences dialog. The project/file config dialog let you choose which compiler configuration to use to build the project/file (you can also override some flags for a specific file in your project, e.g. a module that needs to link to a particular library).

The linter simply follow the project/file configuration.

**Comment by GitMensch** [comment]
This is a good start. What I'd like to see is an option to run a file with "multiple compilers".
Something like:
Choosing the compiler not with a dropdown list but with an option to have multiple compilers. Or maybe a dropdown list for the compiler and a button "secondary compiler(s)" where a dialog pops up and other compilers can be chosen via checkbox. Linter will use the the chosen one. Compile will use this, too, but if compilation is error free the secondary compilers are started.

What do you think about this?

**Comment by ColinDuquesnoy** [comment]
> Or maybe a dropdown list for the compiler and a button "secondary compiler(s)" where a dialog pops up and other compilers can be chosen via checkbox. Linter will use the the chosen one. Compile will use this, too, but if compilation is error free the secondary compilers are started.

This should be fairly easy to implement in HackEdit. The only issue I can see is if the user does not define different build directories per compiler configuration, further compilation might be skipped (since we check mtime)

**Comment by GitMensch** [comment]
The check for different build directories during compiler configuration sound like a good check in the IDE :-)

**Comment by GitMensch** [comment]
Do you split the issue (original one [which I'll recheck]) and the feature request?
I'll check the pre 4.7 soon and would like to check the different vcvars setting, too. Is there any change that you'll update the pre 4.7?

**Comment by ColinDuquesnoy** [comment]
> I'll check the pre 4.7 soon and would like to check the different vcvars setting, too. Is there any change that you'll update the pre 4.7?

Yes I will update the preview in a few hours. I have implemented vcvarsall lookup and I am going to finish "cobc --info" integration in the about dialog.

> Do you split the issue (original one [which I'll recheck]) and the feature request?

Yes I'll split it.

**Comment by ColinDuquesnoy** [comment]
I upload a first preview, here on github: https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview1

**Comment by GitMensch** [comment]
UNC works better now.

Is there a way to hide the cmd window that opens each time on compilation?

Suggestion in general: Only call vcvars once (on startup and on changes to the preference setting), store the result and use it each time you start the compiler.

**Comment by GitMensch** [comment]
The encoding issue is still the same, but still no clear "this can be reproduced in that way", log still doesn't show much :-(

**Comment by ColinDuquesnoy** [comment]
> Is there a way to hide the cmd window that opens each time on compilation?

I'll look into this. (I guess I missed that one because I am using python.exe instead of pythonw.exe)

> Suggestion in general: Only call vcvars once (on startup and on changes to the preference setting), store the result and use it each time you start the compiler.

Yes this would be better. I'll make a new preview build when I get that correct.

> The encoding issue is still the same, but still no clear "this can be reproduced in that way", log still doesn't show much :-(

I'll add a log for the byte array I get just before decoding. This might shed some light on the actual issue.

**Comment by GitMensch** [comment]
Sounds good, I'll retest these issues with next preview-build as soon as you drop a note here.

**Comment by ColinDuquesnoy** [comment]
Another preview is ready: https://www.dropbox.com/s/paufds1mof7slqy/OpenCobolIDE-4.7_Setup.exe?dl=0

**Comment by GitMensch** [comment]
Retested with 4.7 preview 2 - the log helps now:

~~~~~
ERROR::open_cobol_ide.compilers::failed to decode compiler output: b'"\\\\SERVER\\share"\r\nCMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.\r\nUNC-Pfade werden nicht unterst\x81tzt.\r\nStattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.\r\nDer Befehl "subcall_1.bat" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\nDer Befehl "subcall_2.bat" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\nexit 1\r\n'
Traceback (most recent call last):
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\compilers.py", line 402, in compile
  File "c:\python\32-bit\3.4\lib\encodings\cp1252.py", line 15, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 146: character maps to <undefined>
INFO::open_cobol_ide.compilers::compiler process exit code: 0
INFO::open_cobol_ide.compilers::compiler process output: Failed to decode compiler output with encoding cp1252
INFO::open_cobol_ide.compilers::binary file (\\SERVER\share\test.dll) created:  False
DEBUG::open_cobol_ide.compilers::compile results: 0 - [('Failed to decode compiler output with encoding cp1252', 2, -1, 0, None, None, '\\\\SERVER\\share\\test.cob')]
~~~~~

The reason my external batch (with it's children subcall_1.bat and subcall_2.bat) doesn't work is because of UNC paths. Before I fix this I'd like to see the encoding error gone ;-)

The encoding error seems to come up because of the German Umlaut ü \x81 in the error message. I guess you'll be finally able to solve the issue, won't you?

**Comment by ColinDuquesnoy** [comment]
> I guess you'll be finally able to solve the issue, won't you?

Well, yes and no. I've found which encoding to use for your case (cp850) but I cannot find a function in the python library that is able to report the correct encoding once OCIDE run as a frozen application. They all report cp1252 while when running from the console sys.stdout.encoding reports cp850...

Quoting the python documentation:

> on Windows, Python uses the name “mbcs” to refer to whatever the currently configured encoding is

So I am tempted to try to use "mbcs" on windows to decode the process output but also log the results of the various functions I tried.

Thoughts?

**Comment by GitMensch** [comment]
As it sounds that "mbcs" is what python wants to have I suggest to just give it a try. If it doesn't work we check further.

**Comment by GitMensch** [comment]
Is it correct that you are able to reproduce this (only on windows I guess)? If yes please drop the "Cannot reproduce" tag.
And a maybe quite simple solution (for not needing that much preview builds ;-) would be a setting in OCIDE for choosing the parser (set to "auto" by default, one could choose from the others, including mbcs).

**Comment by ColinDuquesnoy** [comment]
> Is it correct that you are able to reproduce this (only on windows I guess)? If yes please drop the "Cannot reproduce" tag.

No I am still not able to reproduce this.

When I tried to compile a UNC pathname with the old technique of using the batch wrapper, I did not get a UnicodeDecodeError but we realized that compilation would nerver work with that technique and that I had to find another way to setup msvc enviromnemnt vars. Now that is fixed unc pathnames compile fine with GnuCOBOL rev411 (vc11).

> And a maybe quite simple solution (for not needing that much preview builds ;-) would be a setting in OCIDE for choosing the encoding (set to "auto" by default, one could choose from the others, including mbcs).

This already exists. Not the way you describe and only for opening files (see http://opencobolide.readthedocs.org/en/latest/faq.html#opencobolide-failed-to-open-a-file-due-to-an-encoding-issue-what-can-i-do). There is an encoding context menu which let you choose additional encodings. You can choose to reload the file with a given encoding. PyQode will first try to load the file with the system encoding. If that fails it will retry using the additional encodings you've defined.

Here the issue happens when decoding the compiler process output (qt returns a raw byte array when reading the process stdout/stderr). IMHO this has nothing to do with the encoding you would define for opening files.

I would expect the process output to follow the encoding found by sys.stdout.encoding. But a GUI application does not have a stdout on windows so I guess this might explain why it fails to find the proper encoding when running as a frozen gui app (or when using pythonw).

> As it sounds that "mbcs" is what python wants to have I suggest to just give it a try. If it doesn't work we check further.

Yes let's try that. I think I'll make a new preview tomorrow if I find the time.

**Comment by ColinDuquesnoy** [comment]
@GitMensch Please recheck with the 3rd (and hopefully the last) preview release: https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview3

**Comment by GitMensch** [comment]
@ColinDuquesnoy cannot check this as the external compiler leads to a traceback :-(
I'll test as soon as I can apply a workaround (no idea where to start) or a new preview is available.

**Comment by ColinDuquesnoy** [comment]
New preview build available: https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview4

**Comment by GitMensch** [comment]
4.7 pre4 changed it only a little bit. I now see an error message:

~~~~~
---------------------------
Exception while compiling a file
---------------------------
An exception occured when compiling '\\\\server\\share\\TEST.COB'.

Error='charmap' codec can't encode character '\x81' in position 30: character maps to <undefined>
---------------------------
OK   
---------------------------
~~~~~

It's good to have the error shown directly to the user, but it's not in the log file any more ?!?

I can see the entry ``'charmap' codec can't encode character '\x81' in position 30: character maps to <undefined>`` in the Issues tab; in Compiler tab I see the full error message (with the one character removed). Therefore a user can "see" the problem and solve it.
In this case the problem is calling an own wrapper-batch and trying to compile a source from UNC-path which cannot work - I'll check moving the wrapper script (which actually calls 2 preparsers and 3 compilers ;-) to powershell *someday*. The quick solution was to switch to a network share (which results in a lagging OCIDE, but this would be a different point...) :-)

**Comment by ColinDuquesnoy** [comment]
The fact that you see ```Exception while compiling a file``` dialog and that the log message has disappeared suggests that the error happens somewhere else (decoding of compiler output is still wrapped in an try/except clause and the log message is still here). Can you post the verbose log output?

**Comment by GitMensch** [comment]
The compiling part of the log is

~~~~~
DEBUG::open_cobol_ide.compilers::dependencies of \\server\share\TEST.COB: []
INFO::open_cobol_ide.controllers.cobol::running compilation thread: ['\\\\server\\share\\TEST.COB']
DEBUG::open_cobol_ide.compilers::detecting file type: server\share\TEST.COB - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.MODULE: 1>
INFO::open_cobol_ide.compilers::compiling \\server\share\TEST.COB
[...]
DEBUG::open_cobol_ide.compilers::output: '"\\\\server\\share"\r\nCMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.\r\nUNC-Pfade werden nicht unterst\x81tzt.\r\nStattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.\r\nFehler - aktuelles Verzeichnis ist das Windows-Verzeichnis!\r\n\r\nVoraussichtlich wurde als Arbeitsverzeichnis ein UNC-Pfad angegeben.\r\nBitte nach Umstellung auf Netzlaufwerk erneut versuchen.\r\n\r\nAbarbeitung wird abgebrochen!\r\n'
~~~~~

**Comment by ColinDuquesnoy** [comment]
I've opted for a radically different approach: instead of trying to decode the output, I use the raw output directly (with a few transformation to avoid double quotes and have correct line endings). Non ASCII characters won't be decoded, instead their hexadecimal value will be shown.

Here is how it looks (I replace the real compiler output by the byte array you had on your system):

![encodingerror1](https://cloud.githubusercontent.com/assets/1681217/10946064/88cf4050-8320-11e5-9362-be6573136e38.png)
![encodingerror2](https://cloud.githubusercontent.com/assets/1681217/10946065/88cffa5e-8320-11e5-80be-0c881130bd0d.png)

**Comment by GitMensch** [comment]
Using the raw output on decode errors is the best solution. Finally solved.
I'll recheck with HackEdit next week and OCIDE 4.7 (is there any rough release schedule yet)?

**Comment by ColinDuquesnoy** [comment]
> is there any rough release schedule yet

Roughly:

Once HackEdit has been released on pypi, I will fist work on OCIDE 4.7 
(without the new installer). That might take one or two week...

Afterwards I will work on the windows installer for HackEdit (and 
packaging for GNU/Linux).
