### ISSUE TITLE
Code folding issues with inline PERFORM

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#319]
The following issues can be seen in the attached image:
![marked_text](https://cloud.githubusercontent.com/assets/6699539/14559536/cb1a7f38-0309-11e6-8388-f24066e0e610.PNG)

* inline ``PERFORM`` cannot be collapsed
* ``END-PERFORM`` is sometimes used as end marker for ``IF``

It's likely not that easy to recognize a ``PERFORM`` as inline as the simplest rule is "if PERFORM is followed by  a procedure name it is an out-of-line PERFORM" and pycode doesn't know anything about procedure names.

Even taken into account that pycode knows about "tags" (procedures, identifiers [including ``FUNCTION``s]) doesn't help for recognizing an out-of-line-perform (which was my first thought). ``PERFORM tag`` can either be a out-of-line perform:

~~~~cobol
       PERFORM sec
       PERFORM sec
        VARYING a FROM 1 BY 1
        UNTIL a = 5
       PERFORM sec a TIMES
       PERFORM par1
       PERFORM par1
        THRU par2
~~~~

or the start of an inline perform:

~~~~cobol
       PERFORM a TIMES
            WRITE stuff(a)
       END-PERFORM
~~~~

Am I wrong and pycode already knows if a tag is a procedure or identifier?

**Comment by ColinDuquesnoy** [comment]
I'll have a look. Maybe today or maybe for another release.

**Comment by GitMensch** [comment]
Just found a sample where collapsing of inline perform works: `PERFORM UNTIL ...` and `PERFORM 5 TIMES ...`.
It looks like you have a word list there (including `UNTIL`, missing `VARYING`).

Another issue that I've recognized: often the markers for code folding will only work correct on reload of the file. The simple `IF` gets a collapse option on write but collapses until the next separator period (which is fine for the start), even if the `END-IF` is added.
When is the recalculation of collapse options triggered?

**Comment by ColinDuquesnoy** [comment]
Nice findings! I'll investigate these during the week end. If you find other folding related isssues don't hesitate to post them here. The more sample I have, the better it will be.

**Comment by ColinDuquesnoy** [comment]
Cobol code folding should work better now, most of the issues you reported should be fixed and I also fixed many other corner cases while browsing the open-cobol contrib folder (many issues seen in cobolmac are fixed).

**Comment by GitMensch** [comment]
Good idea to check open-cobol contrib.
Did you check COBJAPI, too (nice clean code, should work all)?

**Comment by ColinDuquesnoy** [comment]
> Did you check COBJAPI, too (nice clean code, should work all)?

Yes, I just found two other minor issues.

**Comment by ColinDuquesnoy** [comment]
Note that I had to rewrite some parts of the code folding and use a new approach: instead of trying to be smart and identify all possible constructs, code folding is now mostly based on the code indentation (within a section). 

This leads to better results with most of the code samples I've tried. If the code is not indented, only division and section are collapse-able. That should not be a problem with nice clean code and it is a sign that the code is not organised in a readable way so I think it's OK to make that approximation. 

Here are some screenshots regarding inline and out of line performs:

![screenshot_20160419_230137](https://cloud.githubusercontent.com/assets/1681217/14655519/efef1108-0682-11e6-9630-1b73d3362a4f.png)
![screenshot_20160419_230150](https://cloud.githubusercontent.com/assets/1681217/14655518/efeb9b9a-0682-11e6-92a4-fd2853db2207.png)
![screenshot_20160419_230221](https://cloud.githubusercontent.com/assets/1681217/14655517/efeb31e6-0682-11e6-9e4a-0272b5694a5f.png)

**Comment by GitMensch** [comment]
Sounds like a good approach.
I hope that the following would still get the code folding (If not this would be at least a good reason to correct this ;-)

~~~~cobol
PERFORM UNTIL 1
   MOVE A TO B
  MOVE C TO A
  MOVE D TO B
  IF C = D
      COMPUTE C = A + B.
      CALL 'PROG' ON EXCEPTION
          DISPLAY X
        PERFORM Y THRU Z.
~~~~

If you did not add this logic: a separator period `.`ends ALL open "nodes".

**Comment by ColinDuquesnoy** [comment]
> I hope that the following would still get the code folding (If not this would be at least a good reason to correct this ;-)

This mostly worked but highlighted a bug when unfolding, which is now fixed ;-) I also make a few tweaks to work better when there are slightly misindented blocks. Should be good in most cases.

**Comment by GitMensch** [comment]
Thank you.

**Comment by GitMensch** [comment]
Just recognized in 4.7.7.dev24:

~~~~cobol
       78 not-there     value 'empty'.
       77 strpoint          pic 9(03) value 1 comp-5.
       77 strpoint2         pic 9(03) value 1 comp-5.
~~~~

leads to `strpoint` and `strpoint2` being shown as sub-nodes to `not-there` (they all should start there own node). Please check this with current dev version.

**Comment by ColinDuquesnoy** [comment]
> Please check this with current dev version.

Works fine with the new implementation
